# Generated by Django 3.1.4 on 2020-12-08 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guess', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='givesto',
            name='gifted',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='givesto',
            name='gifter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guess',
            name='gifted',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guess_gifted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guess',
            name='gifter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guess_gifter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guess',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guess_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
