# Generated by Django 3.1.4 on 2020-12-08 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guess', '0002_auto_20201208_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='givesto',
            name='game',
        ),
        migrations.RemoveField(
            model_name='givesto',
            name='gifted',
        ),
        migrations.RemoveField(
            model_name='givesto',
            name='gifter',
        ),
        migrations.RemoveField(
            model_name='guess',
            name='game',
        ),
        migrations.RemoveField(
            model_name='guess',
            name='gifted',
        ),
        migrations.RemoveField(
            model_name='guess',
            name='gifter',
        ),
        migrations.RemoveField(
            model_name='guess',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='game',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userteam',
            name='team',
        ),
        migrations.RemoveField(
            model_name='userteam',
            name='user',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='GivesTo',
        ),
        migrations.DeleteModel(
            name='Guess',
        ),
        migrations.DeleteModel(
            name='Teams',
        ),
        migrations.DeleteModel(
            name='UserData',
        ),
        migrations.DeleteModel(
            name='UserTeam',
        ),
    ]
