# Generated by Django 3.1.4 on 2020-12-10 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guess', '0004_game_givesto_guess_teams_userdata_userteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='alias',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
