# Generated by Django 3.1.4 on 2020-12-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guess', '0006_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='endDate',
        ),
        migrations.AddField(
            model_name='game',
            name='days',
            field=models.IntegerField(default=6),
        ),
    ]
