# Generated by Django 3.1.4 on 2020-12-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guess', '0007_auto_20201210_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='endDate',
            field=models.DateTimeField(default=None),
        ),
    ]
