# Generated by Django 3.1.4 on 2020-12-10 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guess', '0008_game_enddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='endDate',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
