# Generated by Django 3.1.4 on 2020-12-12 23:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guess', '0012_auto_20201212_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='days',
            field=models.PositiveSmallIntegerField(default=6, validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='teams',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
