# Generated by Django 3.1.4 on 2020-12-19 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guess', '0015_junior'),
        ('guess', '0015_auto_20201215_2243'),
    ]

    operations = [
    ]
