# Generated by Django 3.1.4 on 2020-12-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guess', '0016_merge_20201219_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gameDay',
            field=models.BooleanField(default=False),
        ),
    ]
