# Generated by Django 3.1.4 on 2020-12-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guess', '0017_game_gameday'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='end',
            field=models.BooleanField(default=False),
        ),
    ]
